### ISSUE TITLE
Not working with the Thermal Comfort integration

### ISSUE THREAD

**Issue by ahmadtawakol** [PiotrMachowski/Home-Assistant-custom-components-Custom-Templates#1]
I tried it with a few different entities and they all seemed to work, except for any of the entities provided by the [Thermal Comfort ](https://github.com/dolezsa/thermal_comfort) integration. It just returns the untranslated state. So instead of `Very Comfortable` it just returns `very_comfortable`

**Comment by PiotrMachowski** [comment]
Related to: https://developers.home-assistant.io/blog/2022/12/01/entity_translations/

**Comment by olibos** [comment]
+1 😉

**Comment by ahmadtawakol** [comment]
Unless I'm missing something, it looks like they're doing it in the same way as in the link you posted. I see the translated state when I add the entity to the UI too. Not sure why it isn't working with this component.

**Comment by PiotrMachowski** [comment]
@ahmadtawakol because code for this component was created 1 year ago and this change has been made effective one month ago 😉 I'm working on it

**Comment by ahmadtawakol** [comment]
Oh, I thought you meant the problem was with the Thermal Comfort component 😅 That makes more sense now...

**Comment by PiotrMachowski** [comment]
Support for new type of translations has been added in `v1.0.1`
