### ISSUE TITLE
[New Feature?] Translate to "default" language

### ISSUE THREAD

**Issue by jkrasinger** [PiotrMachowski/Home-Assistant-custom-components-Custom-Templates#23]
I use this "custom templates" and it work fine.

I would be very interested in having this feature without the need to "explicitly" specify the translation language, instead use the "default" language of the GUI/HA. 
So if i specify a language as a Parameter it will be translated to this specific language, but if i don't use this Language Parameter it will be translated to the "default" language of the system. This makes it possible to change the language by changing the default HA language.

Do you think this is possible?

**Comment by ildar170975** [comment]
> "explicitly" specify the translation language, instead use the "default" language of the GUI/HA.

This is already done in HA 2024.3 - see `state_translated` function in Docs.
In 2024.3 some functionality of this custom plugin was added to the HA core.

**Comment by jkrasinger** [comment]
Thank you for this information, i did not see this in the documentation of 2024.3

Am 19. März 2024 17:45:15 GMT+04:00 schrieb ildar170975 ***@***.***>:
>> "explicitly" specify the translation language, instead use the "default" language of the GUI/HA.
>
>This is already done in HA 2024.3 - see `state_translated` function in Docs.
>In 2024.3 some functionality of this custom plugin was added to the HA core.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PiotrMachowski/Home-Assistant-custom-components-Custom-Templates/issues/23#issuecomment-2007220309
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit Squeaky Mail gesendet.

**Comment by jkrasinger** [comment]
Thanks for the link, I actually overlooked or ignored this point! That helps me at least partially. :+1:

**Comment by ildar170975** [comment]
@jkrasinger 
I think the issue can be closed.

**Comment by PiotrMachowski** [comment]
I'll keep it - I will add this feature to other functions

**Comment by jkrasinger** [comment]
@ildar170975 and @PiotrMachowski : OK, I will leave this issue open for now.

**Comment by PiotrMachowski** [comment]
Added in [v1.4.0](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Custom-Templates/releases/tag/v1.4.0)
