### ISSUE TITLE
Languages list?

### ISSUE THREAD

**Issue by Protoncek** [PiotrMachowski/Home-Assistant-custom-components-Custom-Templates#5]
Hi!
I wonder... which languages are possible to use? And where to find their "shortcuts"? You only menitoned english (en) and dutch (nl). 
Would it be possible to use slovenian (si?... sl?)
thanks!

**Comment by PiotrMachowski** [comment]
Hi, this integration uses Home Assistant built-in translations, so you should be to use every language that is available in languages selection in HA UI.

Most of them are listed [here](https://developers.home-assistant.io/docs/voice/intent-recognition/supported-languages/)

**Comment by Protoncek** [comment]
Aha...thanks, i've got it. It seems that i experienced mix of wrong decisions: 
- first: i took "si" for my language, since usually for Slovenia it's SI,  not SL (SL is supposely Sierra Leone), then i also tried "sl", but it was still in english, because of:
- second: i took you example sun.sun, which isn't translated into slovenian...  :-(
Thaks for really quick help!

**Comment by PiotrMachowski** [comment]
I will add a link to a list of languages to the documentation 👍

**Comment by PiotrMachowski** [comment]
A list of available language tags is available [here](https://github.com/home-assistant/core/blob/master/homeassistant/generated/languages.py), a list of desriptions of language tags is available [here](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)
