### ISSUE TITLE
[FR] Add localization for "unavailable" & "unknown" values

### ISSUE THREAD

**Issue by ildar170975** [PiotrMachowski/Home-Assistant-custom-components-Custom-Templates#6]
These strings represent `unavailable` & `unknown` values:
```
state.default.unavailable
state.default.unknown
```
Currently these strings seem to be not supported:

![изображение](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Custom-Templates/assets/71872483/bf70a48d-e298-48c5-a524-1431b3a99cf6)

It would be great if this plugin provides a localization for these strings.

**Comment by PiotrMachowski** [comment]
Unfortunately these keys are only available in frontend translations, so this integration can't access them

**Comment by PiotrMachowski** [comment]
Yes, they are stored in the HA frontend, which is basically a separate application

https://developers.home-assistant.io/docs/internationalization
